### ISSUE TITLE
Reconnect failure :: receiver

### ISSUE THREAD

**Issue by madkote** [jasonrbriggs/stomp.py#294] opened 2020-03-05 15:29 UTC
Reconnect is not functioning as stated in the documentation.
Source: http://jasonrbriggs.github.io/stomp.py/api.html#dealing-with-disconnects

Code example:
```
import logging
import sys
import time

import stomp


def stomp_connect(conn, user='guest', password='guest', destination='test_queue'):
    conn.connect(login=user, passcode=password, wait=True)
    conn.subscribe(destination=destination, id=1, ack='auto')


class ReconnectListener(stomp.ConnectionListener):
        def __init__(self, conn):
            self.conn = conn

        def on_error(self, headers, message):
            print('received an error "%s"' % message)

        def on_message(self, headers, message):
            print('>> received a message "%s"' % message)
            time.sleep(1)
            print('>> processed message')

        def on_disconnected(self):
            print('disconnected')
            stomp_connect(self.conn)


def demo_publish():
    print()
    print('+----------------------------------------+')
    print('| Single ActiveMQ receiver example         |')
    print('+----------------------------------------+')
    #
    #
    host_and_ports = [('localhost', 61613)]
    attempts = 30
    name_queue = 'test_queue'
    #
    #
    conn = stomp.Connection(
        host_and_ports=host_and_ports,
        reconnect_attempts_max=attempts
    )
    conn.set_listener('', ReconnectListener(conn))
    stomp_connect(conn)
    #
    #
    sleep = 13.0
    try:
        while True:
            try:
                print('>> receiving...')
                print('>>> >>> sleep')
                time.sleep(sleep)
            except KeyboardInterrupt:
                break
    finally:
        print('> disconnect')
        conn.disconnect()
        print('> disconnect done')


if __name__ == '__main__':
    logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
    demo_publish()
```

Normally, messages are received from ActiveMQ.
Then, stop and start the ActiveMQ (with docker-compose).
In this case, the receiver will try to reconnect. But it will not receive messages again...

Steps:
* start ActiveMQ with docker
* start sender from #293 
* start listener above
* let it run.. for some time to see incoming messages
* **STOP** ActiveMQ
* **START** ActiveMQ
* sender from #293 will die...
* start sender from #293
* receiver will reconnect (at least it looks like...) but it will not receive messages.

Output
```
python demo_receive.py 

INFO:stomp.py:attempt reconnection (True, None, 0)
INFO:stomp.py:Attempting connection to host localhost, port 61613
INFO:stomp.py:Established connection to host localhost, port 61613
INFO:stomp.py:Starting receiver loop (<Thread(Thread-1, started daemon 140708256392960)>)
INFO:stomp.py:Created thread <Thread(Thread-1, started daemon 140708256392960)> using func <function default_create_thread at 0x7ff932858cb0>
DEBUG:stomp.py:Sending frame: [b'STOMP', b'\n', b'accept-version:1.1\n', b'login:guest\n', b'passcode:guest\n', b'\n', b'\x00']
DEBUG:stomp.py:Received frame: 'CONNECTED', headers={'server': 'ActiveMQ/5.15.6', 'heart-beat': '0,0', 'session': 'ID:activemq-34371-1583421361979-3:1', 'version': '1.1'}, body=''
DEBUG:stomp.py:Heartbeats calculated (0, 0)
DEBUG:stomp.py:Sending frame: [b'SUBSCRIBE', b'\n', b'ack:auto\n', b'destination:test_queue\n', b'id:1\n', b'\n', b'\x00']
>> receiving...
>>> >>> sleep
>> receiving...
>>> >>> sleep
DEBUG:stomp.py:Received frame: 'MESSAGE', headers={'content-length': '35', 'expires': '0', 'destination': '/queue/test_queue', 'subscription': '1', 'priority': '4', 'message-id': 'ID:activemq-34371-1583421361979-3:2:-1:1:1', 'timestamp': '1583421393236'}, body='message #0, time=1583421393.2346458'
>> received a message "message #0, time=1583421393.2346458"
>> processed message
>> receiving...
>>> >>> sleep
DEBUG:stomp.py:Received frame: 'MESSAGE', headers={'content-length': '35', 'expires': '0', 'destination': '/queue/test_queue', 'subscription': '1', 'priority': '4', 'message-id': 'ID:activemq-34371-1583421361979-3:2:-1:1:2', 'timestamp': '1583421406246'}, body='message #1, time=1583421406.2457302'
>> received a message "message #1, time=1583421406.2457302"
>> processed message
>> receiving...
>>> >>> sleep
DEBUG:stomp.py:Received frame: 'MESSAGE', headers={'content-length': '35', 'expires': '0', 'destination': '/queue/test_queue', 'subscription': '1', 'priority': '4', 'message-id': 'ID:activemq-34371-1583421361979-3:2:-1:1:3', 'timestamp': '1583421419259'}, body='message #2, time=1583421419.2578766'
>> received a message "message #2, time=1583421419.2578766"
>> processed message
>> receiving...
>>> >>> sleep
DEBUG:stomp.py:Received frame: 'MESSAGE', headers={'content-length': '34', 'expires': '0', 'destination': '/queue/test_queue', 'subscription': '1', 'priority': '4', 'message-id': 'ID:activemq-34371-1583421361979-3:2:-1:1:4', 'timestamp': '1583421432266'}, body='message #3, time=1583421432.265517'
>> received a message "message #3, time=1583421432.265517"
>> processed message
DEBUG:stomp.py:nothing received, raising CCE
INFO:stomp.py:Receiver loop ended
disconnected
INFO:stomp.py:attempt reconnection (True, None, 0)
INFO:stomp.py:Attempting connection to host localhost, port 61613
INFO:stomp.py:Established connection to host localhost, port 61613
INFO:stomp.py:Starting receiver loop (<Thread(Thread-2, started daemon 140708248000256)>)
INFO:stomp.py:Created thread <Thread(Thread-2, started daemon 140708248000256)> using func <function default_create_thread at 0x7ff932858cb0>
DEBUG:stomp.py:nothing received, raising CCE
DEBUG:stomp.py:Sending frame: [b'STOMP', b'\n', b'accept-version:1.1\n', b'login:guest\n', b'passcode:guest\n', b'\n', b'\x00']
ERROR:stomp.py:Error sending frame
Traceback (most recent call last):
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/transport.py", line 630, in send
    self.socket.sendall(encoded_frame)
OSError: [Errno 9] Bad file descriptor
INFO:stomp.py:Receiver loop ended
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/transport.py", line 360, in __receiver_loop
    self.notify("disconnected")
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/transport.py", line 230, in notify
    notify_func()
  File "demo_receive.py", line 42, in on_disconnected
    stomp_connect(self.conn)
  File "demo_receive.py", line 24, in stomp_connect
    conn.connect(login=user, passcode=password, wait=True)
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/connect.py", line 162, in connect
    Protocol11.connect(self, *args, **kwargs)
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/protocol.py", line 332, in connect
    self.send_frame(cmd, headers)
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/protocol.py", line 244, in send_frame
    self.transport.transmit(frame)
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/transport.py", line 271, in transmit
    self.send(packed_frame)
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/transport.py", line 634, in send
    raise e
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/transport.py", line 630, in send
    self.socket.sendall(encoded_frame)
OSError: [Errno 9] Bad file descriptor

>> receiving...
>>> >>> sleep
>> receiving...
>>> >>> sleep
>> receiving...
>>> >>> sleep
>> receiving...
>>> >>> sleep
^C> disconnect
  File "demo_receive.py", line 82, in <module>
    demo_publish()
  File "demo_receive.py", line 76, in demo_publish
    conn.disconnect()
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/connect.py", line 172, in disconnect
    Protocol11.disconnect(self, receipt, headers, **keyword_headers)
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/protocol.py", line 351, in disconnect
    traceback.print_stack()
DEBUG:stomp.py:Not sending disconnect, already disconnected
> disconnect done

```

Here is the output of the sender
```
>>>>
>>>> python demo_send.py 
>>>>

....

>> send 3
DEBUG:stomp.py:Sending frame: [b'SEND', b'\n', b'content-length:34\n', b'destination:test_queue\n', b'\n', b'message #3, time=1583421432.265517', b'\x00']
>>> >>> sleep
DEBUG:stomp.py:nothing received, raising CCE
INFO:stomp.py:Receiver loop ended
disconnected
INFO:stomp.py:attempt reconnection (True, None, 0)
INFO:stomp.py:Attempting connection to host localhost, port 61613
INFO:stomp.py:Established connection to host localhost, port 61613
INFO:stomp.py:Starting receiver loop (<Thread(Thread-2, started daemon 140674029373184)>)
DEBUG:stomp.py:nothing received, raising CCE
INFO:stomp.py:Created thread <Thread(Thread-2, started daemon 140674029373184)> using func <function default_create_thread at 0x7ff13aeebcb0>
INFO:stomp.py:Receiver loop ended
DEBUG:stomp.py:Sending frame: [b'STOMP', b'\n', b'accept-version:1.1\n', b'login:guest\n', b'passcode:guest\n', b'\n', b'\x00']
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/transport.py", line 360, in __receiver_loop
    self.notify("disconnected")
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/transport.py", line 230, in notify
    notify_func()
  File "demo_send.py", line 43, in on_disconnected
    stomp_connect(self.conn)
  File "demo_send.py", line 24, in stomp_connect
    conn.connect(login=user, passcode=password, wait=True)
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/connect.py", line 162, in connect
    Protocol11.connect(self, *args, **kwargs)
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/protocol.py", line 332, in connect
    self.send_frame(cmd, headers)
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/protocol.py", line 244, in send_frame
    self.transport.transmit(frame)
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/transport.py", line 271, in transmit
    self.send(packed_frame)
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/transport.py", line 636, in send
    raise exception.NotConnectedException()
stomp.exception.NotConnectedException

>> send 4
DEBUG:stomp.py:Sending frame: [b'SEND', b'\n', b'content-length:35\n', b'destination:test_queue\n', b'\n', b'message #4, time=1583421445.2752912', b'\x00']
> disconnect
  File "demo_send.py", line 89, in <module>
    demo_publish()
  File "demo_send.py", line 83, in demo_publish
    conn.disconnect()
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/connect.py", line 172, in disconnect
    Protocol11.disconnect(self, receipt, headers, **keyword_headers)
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/protocol.py", line 351, in disconnect
    traceback.print_stack()
DEBUG:stomp.py:Not sending disconnect, already disconnected
> disconnect done
Traceback (most recent call last):
  File "demo_send.py", line 89, in <module>
    demo_publish()
  File "demo_send.py", line 74, in demo_publish
    'message #%s, time=%s' % (counter, time.time())
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/protocol.py", line 398, in send
    self.send_frame(CMD_SEND, headers, body)
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/protocol.py", line 244, in send_frame
    self.transport.transmit(frame)
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/transport.py", line 271, in transmit
    self.send(packed_frame)
  File "/home/madkote/demo-stomp/venv/lib/python3.7/site-packages/stomp/transport.py", line 636, in send
    raise exception.NotConnectedException()
stomp.exception.NotConnectedException


>>>>
>>>> python demo_send.py 
>>>>

INFO:stomp.py:attempt reconnection (True, None, 0)
INFO:stomp.py:Attempting connection to host localhost, port 61613
INFO:stomp.py:Established connection to host localhost, port 61613
INFO:stomp.py:Starting receiver loop (<Thread(Thread-1, started daemon 140686526031616)>)
INFO:stomp.py:Created thread <Thread(Thread-1, started daemon 140686526031616)> using func <function default_create_thread at 0x7ff4234a8cb0>
DEBUG:stomp.py:Sending frame: [b'STOMP', b'\n', b'accept-version:1.1\n', b'login:guest\n', b'passcode:guest\n', b'\n', b'\x00']
DEBUG:stomp.py:Received frame: 'CONNECTED', headers={'server': 'ActiveMQ/5.15.6', 'heart-beat': '0,0', 'session': 'ID:activemq-43861-1583421439527-3:1', 'version': '1.1'}, body=''
DEBUG:stomp.py:Heartbeats calculated (0, 0)
>> send 0
DEBUG:stomp.py:Sending frame: [b'SEND', b'\n', b'content-length:35\n', b'destination:test_queue\n', b'\n', b'message #0, time=1583421459.3060532', b'\x00']
>>> >>> sleep
>> send 1
DEBUG:stomp.py:Sending frame: [b'SEND', b'\n', b'content-length:35\n', b'destination:test_queue\n', b'\n', b'message #1, time=1583421472.3106334', b'\x00']
>>> >>> sleep
>> send 2
DEBUG:stomp.py:Sending frame: [b'SEND', b'\n', b'content-length:35\n', b'destination:test_queue\n', b'\n', b'message #2, time=1583421485.3212554', b'\x00']
>>> >>> sleep
^C> disconnect
DEBUG:stomp.py:Sending frame: [b'DISCONNECT', b'\n', b'receipt:40460ce1-6515-44a8-8592-f80fcd3f1126\n', b'\n', b'\x00']
> disconnect done
```

**Please advise**

**Comment by jasonrbriggs** [comment] 2020-06-27 08:10
@madkote Can you try with the latest on the dev branch? There was an issue with disconnect notifications being sent twice, which messed up the reconnection -- there's a fix in dev for this now.

**Comment by madkote** [comment] 2020-06-29 08:46
@jasonrbriggs will do.

**Comment by EvelynSubarrow** [comment] 2020-11-28 12:00
I've got the same problem on 6.1.0 - try to reconnect as the guide says, and sometimes it works, sometimes it silently fails

**Comment by madkote** [comment] 2020-11-30 17:27
@EvelynSubarrow I ended up to write more adapters/wrappers to the `stomp.py` library - since then it is stable.

Also note, it depends which version of ActiveMQ you use and how the storage (persistence) is done. For details consult ActiveMQ FAQ.

**Comment by the01** [comment] 2020-12-01 10:32
@madkote can you share that code?

I'm having the same issue where sometimes after a reconnect the subscription is not active. Is there a way to check whether I am subscribed or not?

**Comment by xiandong79** [comment] 2020-12-02 02:13
stomp.py               6.1.0

```
D [2020-11-30 21:36:57,859] [1606743417.859224] nothing received, raising CCE
I [2020-11-30 21:36:57,859] [1606743417.859558] Receiver loop ended
```

yes, the re-connect does not work sometimes.

**Comment by madkote** [comment] 2020-12-02 10:26
> @madkote can you share that code?
> 
> I'm having the same issue where sometimes after a reconnect the subscription is not active. Is there a way to check whether I am subscribed or not?

@the01 I need to see how much I can share - since this is now part of company's code base.

**Comment by EvelynSubarrow** [comment] 2020-12-02 14:46
> @madkote can you share that code?
> 
> I'm having the same issue where sometimes after a reconnect the subscription is not active. Is there a way to check whether I am subscribed or not?

@the01 I'm afraid it's a little messy, the project in general is in need of overhaul, but if you look in here for the Listener class (and for how it's dealt with in the main loop), you should hopefully be able to understand how I've worked around it. In short it effectively starts the connection process all over again, because a new connection never fails in this way, and uses semaphores to ensure that it only attempts reconnection once per disconnect

https://github.com/EvelynSubarrow/IronSwallow/blob/master/main.py

**Comment by the01** [comment] 2020-12-10 11:45
@EvelynSubarrow thank you for your input.
I noticed some situations where disconnect was not called, but the rx loop just ended or it got stuck on subscribe() which made my code more complicated. So when I tried replacing the connection, it became a mess with threads/locks/.. and I ended up with a run-away race condition where the number of threads was increasing.

**Comment by EvelynSubarrow** [comment] 2020-12-10 19:48
@the01 I've had similar issues, particularly around threading, at one point my solution had a few hundred threads attempting reconnection, not a good time

**Comment by the01** [comment] 2020-12-11 11:59
I think I mostly solved this now. I limited the locations where a reconnect may be triggered, placed the connection and the reconnecting process under a Lock, ran the reconnect in a new thread, set is_running to False on the connection and the transport, terminated the heartbeat, closed the socket, stopped the transport, created a new connection instance, connected and then waited in my own code with timeout (`connect(wait=True)` would sometimes not return).

I'm not sure which of this steps are really necessary, but it seems to run stable now

**Comment by jasonrbriggs** [comment] 2021-04-11 16:49
Closing. Without a reproducible test case (or a patch), won't be looking into this...

**Closed as completed by jasonrbriggs** 2021-04-11 16:49 UTC
Labels: wontfix
